[SERVICE]
    Flush         5
    Daemon        Off
    Log_Level     info
    Parsers_File  /fluent-bit/etc/parsers.conf
    HTTP_Server   On
    HTTP_Listen   0.0.0.0
    HTTP_Port     2020
    Health_Check  On
    HC_Errors_Count  5
    HC_Retry_Failure_Count  5
    HC_Period     60
    storage.metrics  On

[INPUT]
    Name              forward
    Listen            0.0.0.0
    Port              24224
    Buffer_Chunk_Size 1M
    Buffer_Max_Size   6M
    Tag               docker.*

[FILTER]
    Name          parser
    Match         docker.*
    Key_Name      log
    Parser        json
    Reserve_Data  On

[FILTER]
    Name          modify
    Match         docker.*
    Add           cx.application.name wealthwise
    Add           environment production

[FILTER]
    Name          lua
    Match         docker.*
    script        /fluent-bit/etc/subsystem.lua
    call          set_subsystem

[OUTPUT]
    Name                 http
    Match                docker.*
    Host                 ingress.${CX_DOMAIN}
    Port                 443
    URI                  /logs/v1/singles
    Format               json_lines
    Header               Authorization Bearer ${CX_API_KEY}
    Header               Content-Type application/json
    Compress             gzip
    TLS                  On
    TLS.Verify           On
    Retry_Limit          5
    net.keepalive        On
    net.keepalive_idle_timeout  10
