{{- if not .Values.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wealthwise.configMapName" . }}
  namespace: {{ include "wealthwise.namespace" . }}
  labels:
    {{- include "wealthwise.commonLabels" . | nindent 4 }}
data:
  API_PORT: {{ .Values.api.port | quote }}
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  NEXT_TELEMETRY_DISABLED: "1"
  MCP_PORT: {{ .Values.mcp.port | quote }}
  MCP_TRANSPORT: "sse"
  AGENT_PORT: {{ .Values.agenticAi.port | quote }}
{{- end }}
