{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "wealthwise.fullname" . }}-allow-mcp-egress
  namespace: {{ include "wealthwise.namespace" . }}
  labels:
    {{- include "wealthwise.commonLabels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "wealthwise.mcp.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    - ports:
        - protocol: TCP
          port: {{ .Values.networkPolicies.mongodbPort }}
    - ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
{{- end }}
