apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wealthwise-otel-collector
spec:
  template:
    spec:
      containers:
        - name: otel-collector
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
